// i18n — EN mặc định, VI + JA tuỳ chọn. Chuỗi chrome (UI) đa ngữ.
export const languages = { en: "EN", vi: "VI", ja: "JA" } as const;
export type Lang = keyof typeof languages;
export const defaultLang: Lang = "en";

export const ui = {
  en: {
    "nav.home": "Home",
    "nav.journey": "Journey",
    "nav.experience": "Experience",
    "nav.blog": "Blog",
    "nav.news": "News",
    "nav.about": "About",
    "footer.tagline": "Self-updating daily · Grok × Claude · Astro",
    "footer.built": "Built with Astro 5.",
    skip: "Skip to main content",

    // Hero
    "hero.years": "{n}+ years building production systems",
    "hero.cta1": "View career trajectory →",
    "hero.cta2": "Experience",
    "hero.skills": "+{n} production-grade skills",

    // Home — Manifesto
    "home.manifesto.l1": "Systems engineered to outlive their creators.",
    "home.manifesto.l2":
      "Intelligence embedded into architecture — never retrofitted.",
    "home.manifesto.l3":
      "Infrastructure that compounds value instead of accumulating technical debt.",

    // Home — Solves
    "home.solve.eyebrow": "Problems solved in production",
    "home.solve.title": "What I systematically dismantle",
    "home.solve.sub":
      "A representative sample — not the full list. Each one taken from diagnosis to production, built on systems thinking that transfers to the next problem.",

    // Home — Skills
    "home.skills.eyebrow": "Technical DNA",
    "home.skills.title": "From interface to inference pipeline",
    "home.skills.sub":
      "A complete, battle-tested stack spanning frontend architecture, backend systems, cloud infrastructure, and production AI integration.",
    "home.skills.total": "{n} skills across {g} domains",

    // Home — Focus
    "home.focus.eyebrow": "Current focus",
    "home.focus.cta": "View full roadmap →",

    // Home — Journey
    "home.journey.eyebrow": "Career trajectory",
    "home.journey.title": "{n} milestones. One continuous arc.",
    "home.journey.cta": "Explore the full journey →",

    // Home — Blog & News
    "home.blog.eyebrow": "Writing",
    "home.blog.title": "Latest writing",
    "home.news.eyebrow": "Tech radar",
    "home.news.title": "Curated by Grok — realtime",

    "common.all": "View all →",
    "common.readmin": "{n} min read",

    // Roadmap
    "roadmap.eyebrow": "Trajectory",
    "roadmap.title": "Roadmap",
    "roadmap.sub":
      "From current AI systems work to long-term architectural leadership.",

    "status.done": "Completed",
    "status.in-progress": "In progress",
    "status.planned": "Planned",

    // Journey page
    "journey.eyebrow": "Flight Log",
    "journey.title": "Journey",
    "journey.sub":
      "Navigate by narrative chapters or switch to chronological timeline.",
    "journey.hint": "Scroll to advance · Toggle view below",
    "journey.cta": "View detailed experience →",
    "journey.view.chapters": "Narrative",
    "journey.view.timeline": "Timeline",
    "journey.chapter": "Chapter",
    "journey.hud.sector": "Sector",
    "journey.hud.progress": "Progress",

    // Experience
    "exp.eyebrow": "Career",
    "exp.title": "Professional Experience",
    "exp.sub":
      "From frontend development to AI systems architecture and production optimization.",
    "exp.update": "Last updated {date}",
    "exp.byGrok": "Auto-generated by Grok",
    "exp.side.eyebrow": "Side projects",
    "exp.side.title": "Personal projects",
    "exp.edu.eyebrow": "Education",
    "exp.edu.title": "Education",

    // About
    "about.eyebrow": "About",
    "about.title": "About",
    "about.contact": "Contact",
    "about.languages": "Languages",
    "about.meta.title": "About this portfolio",
    "about.meta.body":
      'A self-updating portfolio built on a multi-AI pipeline: <b>Grok</b> continuously scans realtime technology developments and produces written content, while <b>Claude</b> maintains architectural integrity and implements the site using <span class="mono">Astro</span>. A daily GitHub Action triggers content generation, validation, and automated deployment.',
    "about.oldPortfolio": "Previous portfolio ↗",

    // Blog
    "blog.eyebrow": "Writing · auto-updated",
    "blog.title": "Blog",
    "blog.description": "{n} posts on production systems, AI agents, architecture, and cost optimisation — written and auto-updated daily.",
    "blog.sub":
      "{n} posts — written by Grok with focus on production systems, architecture, and AI integration.",
    "blog.empty":
      "No posts published yet. The pipeline will generate the first entry.",
    "blog.backToGrok":
      "Generated in realtime by Grok and published through the Claude × Grok content pipeline.",

    // News
    "news.eyebrow": "Tech radar · auto-updated",
    "news.title": "Tech news",
    "news.sub":
      "{count} items across {days} days — filtered and synthesized by Grok according to my technical focus areas.",
    "news.empty":
      "No news items yet. The pipeline will populate the first batch.",
    "news.filterAll": "All",
    "news.noMatch": "No items match the selected filters.",
    "news.featured": "Featured",

    // 404
    "notfound.eyebrow": "404",
    "notfound.title": "Page not found",
    "notfound.body":
      "The requested page does not exist or has been moved. Return to the homepage or explore recent content below.",
    "notfound.home": "Return home",
    "notfound.latestBlog": "Latest writing",
    "notfound.radar": "Tech radar",
  },

  // ==================== VIETNAMESE ====================
  vi: {
    "nav.home": "Trang chủ",
    "nav.journey": "Hành trình",
    "nav.experience": "Kinh nghiệm",
    "nav.blog": "Blog",
    "nav.news": "Tin tức",
    "nav.about": "Giới thiệu",
    "footer.tagline": "Tự cập nhật hằng ngày · Grok × Claude · Astro",
    "footer.built": "Xây dựng bằng Astro 5.",
    skip: "Chuyển đến nội dung chính",

    "hero.years": "{n}+ năm xây dựng hệ thống production",
    "hero.cta1": "Xem quỹ đạo nghề nghiệp →",
    "hero.cta2": "Kinh nghiệm",
    "hero.skills": "+{n} kỹ năng production",

    "home.manifesto.l1":
      "Hệ thống được thiết kế để tồn tại lâu dài hơn cả người kiến tạo.",
    "home.manifesto.l2":
      "Trí tuệ được tích hợp vào kiến trúc — không phải gắn thêm vào sau.",
    "home.manifesto.l3":
      "Hạ tầng tạo ra giá trị tích lũy thay vì tích tụ nợ kỹ thuật.",

    "home.solve.eyebrow": "Bài toán đã giải quyết trong production",
    "home.solve.title": "Những thách thức tôi thường xuyên tháo gỡ",
    "home.solve.sub":
      "Vài bài toán tiêu biểu — không phải tất cả. Mỗi cái đi từ chẩn đoán đến production, trên nền tư duy hệ thống áp dụng được cho bài toán tiếp theo.",

    "home.skills.eyebrow": "Technical DNA",
    "home.skills.title": "Từ giao diện đến inference pipeline",
    "home.skills.sub":
      "Một stack hoàn chỉnh, đã được kiểm chứng qua môi trường production — từ frontend architecture đến tích hợp AI.",
    "home.skills.total": "{n} kỹ năng trên {g} lĩnh vực",

    "home.focus.eyebrow": "Hướng đi hiện tại",
    "home.focus.cta": "Xem lộ trình chi tiết →",

    "home.journey.eyebrow": "Quỹ đạo nghề nghiệp",
    "home.journey.title": "{n} mốc quan trọng · Một quỹ đạo liên tục",
    "home.journey.cta": "Khám phá hành trình →",

    "home.blog.eyebrow": "Viết lách",
    "home.blog.title": "Bài viết mới nhất",
    "home.news.eyebrow": "Tech radar",
    "home.news.title": "Tin công nghệ được Grok tổng hợp",

    "common.all": "Xem tất cả →",
    "common.readmin": "{n} phút đọc",

    "roadmap.eyebrow": "Trajectory",
    "roadmap.title": "Lộ trình phát triển",
    "roadmap.sub":
      "Từ công việc hệ thống AI hiện tại đến vị trí lãnh đạo kiến trúc dài hạn.",

    "status.done": "Hoàn thành",
    "status.in-progress": "Đang thực hiện",
    "status.planned": "Kế hoạch",

    "journey.eyebrow": "Flight Log",
    "journey.title": "Hành trình",
    "journey.sub":
      "Điều hướng theo chương chuyện hoặc chuyển sang dạng mốc thời gian.",
    "journey.hint": "Cuộn để di chuyển · Thay đổi chế độ xem bên dưới",
    "journey.cta": "Xem kinh nghiệm chi tiết →",
    "journey.view.chapters": "Theo chương",
    "journey.view.timeline": "Mốc thời gian",
    "journey.chapter": "Chương",
    "journey.hud.sector": "Lĩnh vực",
    "journey.hud.progress": "Tiến độ",

    "exp.eyebrow": "Sự nghiệp",
    "exp.title": "Kinh nghiệm làm việc",
    "exp.sub":
      "Từ phát triển frontend đến kiến trúc hệ thống và tối ưu hóa AI trong production.",
    "exp.update": "Cập nhật lần cuối {date}",
    "exp.byGrok": "Tự động tạo bởi Grok",
    "exp.side.eyebrow": "Dự án cá nhân",
    "exp.side.title": "Dự án cá nhân",
    "exp.edu.eyebrow": "Học vấn",
    "exp.edu.title": "Học vấn",

    "about.eyebrow": "Giới thiệu",
    "about.title": "Giới thiệu",
    "about.contact": "Liên hệ",
    "about.languages": "Ngôn ngữ",
    "about.meta.title": "Về portfolio này",
    "about.meta.body":
      'Một portfolio tự cập nhật hằng ngày theo mô hình multi-AI pipeline: <b>Grok</b> liên tục quét các phát triển công nghệ realtime và tạo nội dung viết, trong khi <b>Claude</b> duy trì tính toàn vẹn kiến trúc và triển khai site bằng <span class="mono">Astro</span>. Mỗi ngày một GitHub Action kích hoạt quá trình sinh nội dung, kiểm tra và tự động triển khai.',

    "about.oldPortfolio": "Portfolio cũ ↗",

    "blog.eyebrow": "Viết lách · tự cập nhật",
    "blog.title": "Blog",
    "blog.description": "{n} bài viết về hệ thống production, AI agent, kiến trúc và tối ưu chi phí — được Grok tạo và cập nhật mỗi ngày.",
    "blog.sub":
      "{n} bài viết — được Grok tạo ra mỗi ngày với trọng tâm là hệ thống production, kiến trúc và tích hợp AI.",
    "blog.empty": "Chưa có bài viết. Pipeline sẽ tự động sinh bài đầu tiên.",
    "blog.backToGrok":
      "Bài viết được tạo tự động bởi Grok theo thời gian thực và xuất bản qua pipeline Claude × Grok.",

    "news.eyebrow": "Tech radar · tự cập nhật",
    "news.title": "Tin công nghệ",
    "news.sub":
      "{count} tin trong {days} ngày — được Grok lọc và tổng hợp theo các lĩnh vực kỹ thuật trọng tâm của tôi.",
    "news.empty": "Chưa có tin tức. Pipeline sẽ tự động sinh batch đầu tiên.",
    "news.filterAll": "Tất cả",
    "news.noMatch": "Không có tin nào khớp với bộ lọc hiện tại.",
    "news.featured": "Nổi bật",

    "notfound.eyebrow": "404",
    "notfound.title": "Không tìm thấy trang",
    "notfound.body":
      "Trang bạn yêu cầu không tồn tại hoặc đã được di chuyển. Quay về trang chủ hoặc khám phá nội dung mới nhất bên dưới.",
    "notfound.home": "Về trang chủ",
    "notfound.latestBlog": "Bài viết mới nhất",
    "notfound.radar": "Tech radar",
  },

  // ==================== JAPANESE ====================
  ja: {
    "nav.home": "ホーム",
    "nav.journey": "キャリア",
    "nav.experience": "経験",
    "nav.blog": "ブログ",
    "nav.news": "ニュース",
    "nav.about": "自己紹介",
    "footer.tagline": "毎日自動更新 · Grok × Claude · Astro",
    "footer.built": "Astro 5で構築。",
    skip: "コンテンツへ移動",

    "hero.years": "{n}年以上の実務経験",
    "hero.cta1": "キャリア軌跡を見る →",
    "hero.cta2": "経験",
    "hero.skills": "+{n}の生産環境スキル",

    "home.manifesto.l1": "作成者を超えて存続するシステムを。",
    "home.manifesto.l2":
      "知能はアーキテクチャに織り込まれる — 後付けではない。",
    "home.manifesto.l3": "技術的負債を蓄積せず、価値を積み上げるインフラを。",

    "home.solve.eyebrow": "本番環境で解決した課題",
    "home.solve.title": "体系的に解決する問題領域",
    "home.solve.sub":
      "代表的な事例であり、これが全てではありません。いずれも診断から本番まで手がけ、その背後にあるシステム思考は次の課題にも応用できます。",

    "home.skills.eyebrow": "Technical DNA",
    "home.skills.title": "UIから推論パイプラインまで",
    "home.skills.sub":
      "本番環境で鍛えられた、フロントエンドからAI統合までを含む完全な技術スタック。",
    "home.skills.total": "{g}領域 · {n}スキル",

    "home.focus.eyebrow": "現在の焦点",
    "home.focus.cta": "ロードマップを見る →",

    "home.journey.eyebrow": "キャリア軌跡",
    "home.journey.title": "{n}のマイルストーン · 1つの連続した軌跡",
    "home.journey.cta": "キャリアを探索する →",

    "home.blog.eyebrow": "執筆",
    "home.blog.title": "最新の記事",
    "home.news.eyebrow": "Tech radar",
    "home.news.title": "Grokがリアルタイムで更新",

    "common.all": "すべて見る →",
    "common.readmin": "約{n}分で読めます",

    "roadmap.eyebrow": "Trajectory",
    "roadmap.title": "今後のロードマップ",
    "roadmap.sub":
      "現在のAIシステムの仕事から長期的なアーキテクチャリーダーシップへ。",

    "status.done": "完了",
    "status.in-progress": "進行中",
    "status.planned": "予定",

    "journey.eyebrow": "Flight Log",
    "journey.title": "キャリア",
    "journey.sub":
      "ナラティブの章で移動するか、タイムライン表示に切り替えます。",
    "journey.hint": "スクロールで前進 · 表示を切り替え",
    "journey.cta": "詳細な経験を見る →",
    "journey.view.chapters": "ナラティブ",
    "journey.view.timeline": "タイムライン",
    "journey.chapter": "チャプター",
    "journey.hud.sector": "セクター",
    "journey.hud.progress": "進行状況",

    "exp.eyebrow": "キャリア",
    "exp.title": "職務経験",
    "exp.sub":
      "フロントエンド開発からAIシステムアーキテクチャと本番最適化まで。",
    "exp.update": "最終更新 {date}",
    "exp.byGrok": "Grokによる自動生成",
    "exp.side.eyebrow": "サイドプロジェクト",
    "exp.side.title": "個人プロジェクト",
    "exp.edu.eyebrow": "学歴",
    "exp.edu.title": "学歴",

    "about.eyebrow": "自己紹介",
    "about.title": "自己紹介",
    "about.contact": "連絡先",
    "about.languages": "言語",
    "about.meta.title": "このポートフォリオについて",
    "about.meta.body":
      'マルチAIパイプラインによって毎日自動更新されるポートフォリオ：<b>Grok</b>がリアルタイムの技術開発を継続的にスキャンしてコンテンツを生成し、<b>Claude</b>がアーキテクチャの整合性を維持しながら<span class="mono">Astro</span>でサイトを実装します。毎日のGitHub Actionがコンテンツ生成・検証・自動デプロイを実行します。',

    "about.oldPortfolio": "旧ポートフォリオ ↗",

    "blog.eyebrow": "執筆 · 毎日自動更新",
    "blog.title": "ブログ",
    "blog.description": "{n}件の記事 — 生産システム、AIエージェント、アーキテクチャ、コスト最適化について。毎日自動更新。",
    "blog.sub":
      "{n}件の記事 — Grokが毎日生成し、生産システム、アーキテクチャ、AI統合に焦点を当てています。",
    "blog.empty":
      "まだ記事がありません。パイプラインが最初の記事を生成します。",
    "blog.backToGrok":
      "Grokによってリアルタイムで生成され、Claude × Grokパイプラインを通じて公開されています。",

    "news.eyebrow": "Tech radar · 毎日自動更新",
    "news.title": "テックニュース",
    "news.sub":
      "{days}日間で{count}件 — Grokが私の技術的関心領域に合わせて毎日リアルタイムでフィルタリング・合成しています。",
    "news.empty":
      "まだニュースがありません。パイプラインが最初のバッチを生成します。",
    "news.filterAll": "すべて",
    "news.noMatch": "選択したフィルターに一致するニュースはありません。",
    "news.featured": "注目",

    "notfound.eyebrow": "404",
    "notfound.title": "ページが見つかりません",
    "notfound.body":
      "要求されたページは存在しないか、移動されています。ホームに戻るか、最新のコンテンツをご覧ください。",
    "notfound.home": "ホームへ戻る",
    "notfound.latestBlog": "最新の記事",
    "notfound.radar": "Tech radar",
  },
} as const;

export function getLangFromUrl(url: URL): Lang {
  const seg = url.pathname.split("/").filter(Boolean)[0];
  if (seg === "vi") return "vi";
  if (seg === "ja") return "ja";
  return "en";
}

export function useTranslations(lang: Lang) {
  return function t(
    key: keyof (typeof ui)["en"],
    vars?: Record<string, string | number>,
  ): string {
    let s: string =
      (ui[lang] as any)[key] ?? (ui.en as any)[key] ?? String(key);
    if (vars)
      for (const [k, v] of Object.entries(vars))
        s = s.replaceAll(`{${k}}`, String(v));
    return s;
  };
}

/** Tạo đường dẫn theo locale: en -> /path, vi -> /vi/path, ja -> /ja/path. */
export function localizedPath(path: string, lang: Lang): string {
  const clean = "/" + path.replace(/^\//, "");
  if (lang === "vi") return "/vi" + (clean === "/" ? "" : clean);
  if (lang === "ja") return "/ja" + (clean === "/" ? "" : clean);
  return clean;
}
